
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author asus
 */
public class PesanKopi extends javax.swing.JFrame {
    private Integer totalHarga;

    /**
     * Creates new form PesanKopi
     */
    public PesanKopi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        eKeluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        eJenis = new javax.swing.JComboBox<>();
        eJumlahP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ePesan = new javax.swing.JButton();
        eReset = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        aJumlah = new javax.swing.JLabel();
        aTotal = new javax.swing.JLabel();
        aJenis = new javax.swing.JLabel();
        eSimpan = new javax.swing.JButton();
        eHarga = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pngegg (34) (1).png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 0, 70, 80);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Alun - alun");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(80, 30, 70, 20);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Surabaya");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(110, 50, 60, 16);

        jLabel9.setText("Kota");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(80, 50, 50, 16);

        jLabel3.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jLabel3.setText("DI KOPI IN DULU");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 70, 220, 40);

        jPanel2.setBackground(new java.awt.Color(204, 102, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(240, -40, 10, 70);

        jPanel3.setBackground(new java.awt.Color(204, 102, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(260, -50, 10, 130);

        jPanel1.setBackground(new java.awt.Color(204, 102, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(280, 0, 10, 130);

        jPanel7.setBackground(new java.awt.Color(204, 102, 0));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel7);
        jPanel7.setBounds(300, 0, 10, 110);

        jPanel5.setBackground(new java.awt.Color(204, 102, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(320, 0, 10, 160);

        jPanel6.setBackground(new java.awt.Color(204, 102, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6);
        jPanel6.setBounds(300, 120, 10, 160);

        eKeluar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pngegg (36) (1).png"))); // NOI18N
        eKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(eKeluar);
        eKeluar.setBounds(290, 490, 40, 40);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Total :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 420, 100, 20);

        eJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ">>PILIH COFFE<<", "CAPPUCINO", "ESPRESSO", "CORRETTO", "AMERICANO", "MAROCCHINO" }));
        getContentPane().add(eJenis);
        eJenis.setBounds(150, 132, 130, 30);
        getContentPane().add(eJumlahP);
        eJumlahP.setBounds(150, 180, 130, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Jenis Kopi :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 130, 80, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Jumlah Pesanan :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 180, 100, 30);

        ePesan.setBackground(new java.awt.Color(204, 102, 0));
        ePesan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ePesan.setForeground(new java.awt.Color(255, 255, 255));
        ePesan.setText("PESAN");
        ePesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ePesanActionPerformed(evt);
            }
        });
        getContentPane().add(ePesan);
        ePesan.setBounds(60, 260, 90, 23);

        eReset.setBackground(new java.awt.Color(204, 102, 0));
        eReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eReset.setForeground(new java.awt.Color(255, 255, 255));
        eReset.setText("RESET");
        eReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eResetActionPerformed(evt);
            }
        });
        getContentPane().add(eReset);
        eReset.setBounds(190, 260, 90, 23);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Harga :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 220, 100, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 102, 0));
        jLabel7.setText("Pesanan");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 290, 100, 20);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Jenis Kopi :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 320, 100, 20);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Jumlah :");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(50, 350, 100, 20);

        aJumlah.setText("...");
        getContentPane().add(aJumlah);
        aJumlah.setBounds(150, 350, 110, 16);

        aTotal.setText("...");
        getContentPane().add(aTotal);
        aTotal.setBounds(150, 420, 110, 16);

        aJenis.setText("...");
        getContentPane().add(aJenis);
        aJenis.setBounds(150, 320, 110, 16);

        eSimpan.setBackground(new java.awt.Color(204, 102, 0));
        eSimpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eSimpan.setForeground(new java.awt.Color(255, 255, 255));
        eSimpan.setText("SIMPAN");
        eSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(eSimpan);
        eSimpan.setBounds(120, 490, 90, 23);

        eHarga.setText("...");
        getContentPane().add(eHarga);
        eHarga.setBounds(150, 220, 130, 30);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/00000BG (2).jpeg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 330, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_eKeluarActionPerformed

    private void ePesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ePesanActionPerformed
        String item = eJenis.getSelectedItem().toString();
        String jumlah = eJumlahP.getText();
        Integer harga = null;
        if(item.equals("CAPPUCINO")){
            harga = 10000;
        }else if(item.equals(("ESPRESSO"))){
            harga = 21000;
        }else if(item.equals("CORRETTO")){
            harga = 27000;
        }else if(item.equals("AMERICANO")){
            harga = 32000;
        }else if(item.equals("MAROCCHINO")){
            harga = 31000;
        }else{
            JOptionPane.showMessageDialog(null, "Pesan apa bang?", "Pilih dan Input Jumlah pesanan dahulu", JOptionPane.ERROR_MESSAGE);
        }
        
      
        Integer totalHarga = harga * Integer.parseInt(jumlah);
             
        aJenis.setText(item);
        eHarga.setText("Rp. "+harga.toString());
        aJumlah.setText(jumlah.toString());
        aTotal.setText("Rp. "+totalHarga.toString());
    }//GEN-LAST:event_ePesanActionPerformed

    private void eResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eResetActionPerformed
        eJenis.setSelectedIndex(0);
        eJumlahP.setText("");
        eHarga.setText("...");
        aJenis.setText("...");
        aJumlah.setText("...");
        aTotal.setText("...");
    }//GEN-LAST:event_eResetActionPerformed

    private void eSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eSimpanActionPerformed
        String jenis = aJenis.getText();
        String jumlah = aJumlah.getText();
        String hargasatu = eHarga.getText();
        String total = aTotal.getText();
        
        JOptionPane.showMessageDialog(this, "Jenis Kopi : " + jenis + "\nJumlah : "+ jumlah + "\nHarga Satuan : " + hargasatu + "\nTotal Harga : Rp." + total);
    }//GEN-LAST:event_eSimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesanKopi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesanKopi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesanKopi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesanKopi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesanKopi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aJenis;
    private javax.swing.JLabel aJumlah;
    private javax.swing.JLabel aTotal;
    private javax.swing.JLabel background;
    private javax.swing.JLabel eHarga;
    private javax.swing.JComboBox<String> eJenis;
    private javax.swing.JTextField eJumlahP;
    private javax.swing.JButton eKeluar;
    private javax.swing.JButton ePesan;
    private javax.swing.JButton eReset;
    private javax.swing.JButton eSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
